apiVersion: v1
kind: Service
metadata:
  name: customer2es-service1
  namespace: customer2es  # namespace the same deployement
spec:
  selector:
    app: customer2es-app1  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 7001           # Port extenal
      targetPort: 7001       # Port in container
      #- protocol: TCP
      #port: 7002           # Port extenal
      #targetPort: 7002       # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
